import React from 'react'
import type { Metadata } from 'next'
import './globals.css'
import iranSans from '@utils/localFonts'
import { Locale, i18n } from '@root/i18n.config'

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: { lang: Locale }
}) {


  return (
    <html lang="en">
      <body className={iranSans.className}>{children}</body>
    </html>
  )
}
