
import { useLocale } from 'next-intl'
import './globals.css'
import { notFound } from 'next/navigation'
import iranSans from '@utils/localFonts'
import { isRtlLang } from 'rtl-detect'
import Layout from '@layouts/Layout'
import { NextIntlClientProvider } from 'next-intl'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {
  const local = useLocale()
  const isRtl = isRtlLang(local)

  if (locale !== local) {
    notFound()
  }

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} dir={isRtl ? "rtl" : "ltr"} >
      <body className={iranSans.className} data-theme="Arenap_theme">
        <NextIntlClientProvider locale={local} messages={messages}>
          <Layout>
            {children}
          </Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
